base/urls.py
# Add urls here to connect views

from django.urls import path
from . import views

app_name="base"
urlpatterns = [
    path('', views.home, name="home"),
    path("login/", views.loginView, name="login"),
    path("register/", views.registerUser, name="register"),
    path("logout/", views.logoutView, name="logout"),
    path("<int:user_id>/dashboard/calendar/", views.calendar, name="calendar"),
    path('<int:user_id>/dashboard/search/', views.search, name="search"),
    path("<int:user_id>/dashboard/", views.dashboard, name="dashboard"),
    path("<int:user_id>/dashboard/myPlans/", views.myPlans, name="myPlans"),
    path("<int:user_id>/dashboard/myPlans/createPlan/", views.createPlan, name="createPlan"),
    path("<int:user_id>/dashboard/myPlans/create/", views.create, name="create"),
    path("<int:user_id>/dashboard/myPlans/deletePlan/", views.deletePlan, name="deletePlan"),
    path("<int:user_id>/dashboard/myPlans/delete/", views.delete, name="delete"),
    path("<int:user_id>/dashboard/myPlans/createWorkout/", views.createWorkout, name="createWorkout"),
    path("<int:user_id>/dashboard/myPlans/createWork/", views.createWork, name="createWork"),
    path("<int:user_id>/dashboard/myPlans/deleteWorkout/", views.deleteWorkout, name="deleteWorkout"),
    path("<int:user_id>/dashboard/myPlans/deleteWork/", views.deleteWork, name="deleteWork"),
    path("<int:user_id>/dashboard/myPlans/<int:plan_id>/", views.planWorkout, name="planWorkout"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/DashboardPage.html
{% include 'navbar.html' %}
{% load static %}
{% block content %}
<div class="dashboard-container">
    <div class="search-container">
        <form action="{% url 'base:search' user_id=user_id %}" method="post" class="search-bar">
            {% csrf_token %}
            <input type="text" placeholder="Search" name="q">
            <button type="submit"><i class='bx bx-search-alt-2'></i></button>
        </form>
    </div>
    <div class="tab-content">
        <div id="box1">
            <a href="myPlans/" style="text-align: center; color: inherit;">
                <h1>View my plans</h1>
            </a>
        </div>
        <div id="box2">
            <h1 style="text-align: center">Today's Workout</h1>
        </div>
        <div id="box3">
            <h1 style="text-align: center">Tomorrow's Workout</h1>
        </div>
    </div>
</div>
{% endblock content %}

templates/createPlan.html
{% include 'navbar.html' %}
{% load static %}
{% block content %}
<div class="createPlan">
    <h1 id="title">Creating Plan with {{ user }}'s workouts</h1>
    <form action="{% url 'base:create' user_id=user_id %}" method="post">
        {% csrf_token %}
        Plan name: <input type="text" name="title">
        {% if workout_list %}
        <br>Select workouts to include:
        <select name="workouts">
            {% for work in workout_list %}
            {% if work.user_id == user_id %}
            <option value="{{ work.id }}">{{ work.title }}</option>
            {% endif %}
            {% endfor %}
        </select>
        <br>Description: <input type="text" name="textfield">
        {% endif %}
        <input type="submit" name="Submit" value="Submit">
        <input type="reset" name="Submit2" value="Reset">
    </form>
</div>

{% endblock %}A

templates/createWorkout.html
{% include 'navbar.html' %}
{% load static %}
{% block content %}
<div class="createWorkout">
    <h1 id="title">Creating workout with {{ user }}</h1>
    <form action="{% url 'base:createWork' user_id=user_id %}" method="post">
        {% csrf_token %}
        Workout name: <input type="text" name="title">
        {% if baseWorkout_list %}
        <br>Select workouts to include:
        <select name="workouts">
            {% for work in baseWorkout_list %}
            <option value="{{ work.id }}">{{ work.name }}</option>
            {% endfor %}
        </select>
        <br>Time: <input type="text" name="textfield"> minutes

        <br>
        <input type="submit" name="Submit" value="Submit">
        <input type="reset" name="Submit2" value="Reset">
        {% endif %}
    </form>
</div>
{% endblock content %}

templates/deletePlan.html
{% include 'navbar.html' %}
{% load static %}
{% block content %}
<div class="deletePlan">
    <h1 id="title">Delete plan with {{ user }}</h1>
    <form action="{% url 'base:delete' user_id=user_id %}" method="post">
        {% csrf_token %}
        {% if plan_list %}
        <br>Select plan to delete:
        <select name="plan">
            {% for plan in plan_list %}
                {% if plan.user_id == user_id %}
                    <option value="{{ plan.id }}">{{ plan.name }}</option>
                    {% endif %}
            {% endfor %}
        </select>
        {% endif %}
        <input type="submit" name="Submit" value="Submit">
        <input type="reset" name="Submit2" value="Reset">
    </form>
</div>

{% endblock content %}

templates/deleteWorkout.html
{% include 'navbar.html' %}
{% load static %}
{% block content %}
<div class="deleteWorkout">
    <h1 id="title">Deleting workout with {{ user }}</h1>
    <form action="{% url 'base:deleteWork' user_id=user_id %}" method="post">
        {% csrf_token %}
        {% if workoutList %}
        <br>Select workout to delete:
        <select name="workout">
            {% for work in workoutList %}
            {% if work.user_id == user_id %}
            <option value="{{ work.id }}">{{ work.title }}</option>
            {% endif %}
            {% endfor %}
        </select>
        <br>
        <input type="submit" name="Submit" value="Submit">
        <input type="reset" name="Submit2" value="Reset">
        {% endif %}

    </form>
</div>
{% endblock content %}

templates/index.html
{% include 'navbar.html' %}
{% load static %}
{% block content %}
<body>
    <h1>Welcome</h1>
</body>
{% endblock content %}

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <script src="{% static 'js/script.js' %}"></script>
</head>

<body>
    {% block content %}

    {% endblock content %}
</body>

</html>

templates/myPlans.html
{% include 'navbar.html' %}
{% load static %}
{% block content %}
<div class="myPlans">
    <div class="myPlans-title">
        <h1>{{ user }}'s Plans</h1>
    </div>

    <div class="myPlans-container">
        <div class="myPlans-plans">
            <p>
                {% if plans_list %}
            <ul>
                {% for plan in plans_list %}
                {% if plan.user_id == user_id %}
                <li><a href="{{ plan.id }}/">{{ plan.name }}</a></li>
                {{ plan.description }}<br>
                {% endif %}
                {% endfor %}
            </ul>
            {% else %}
            <p>No plans created</p>
            {% endif %}
            </p>
        </div>

        <div class="myPlans-items">
            <a href="createPlan/"><button>Create new plan</button></a>
            <a href="deletePlan/"><button>Delete a plan</button></a>
            <a href="createWorkout/"><button>Create workout</button></a>
            <a href="deleteWorkout/"><button>Delete workout</button></a>
        </div>
    </div>
</div>
{% endblock content %}

templates/navbar.html
{% extends 'main.html' %}
{% load static %}
{% block content %}
<body>
    <nav>
        <div class="nav-logo">
            <a href="{% url 'base:home' %}">
                <img src="{% static 'images/AdaptivDevLogo.png' %}" alt="AdaptiveFit Logo">
            </a>
        </div>
        <div class="toggle">
            <a href="#"><i class='bx bx-menu'></i></a>
        </div>
        <ul class="menu">
            <li><a href="{% url 'base:home' %}">Home</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'base:dashboard' user_id=user_id %}">Dashboard</a></li>
                <li><a href="#">Tracker</a></li>
                <li><a href="{% url 'base:myPlans' user_id=user_id %}">My Plans</a></li>
                <li><a href="{% url 'base:calendar' user_id=user_id %}">Calendar</a></li>
                <li><a href="{% url 'base:logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'base:login' %}">Login</a></li>
                <li><a href="{% url 'base:register' %}">Register</a></li>
            {% endif %}
        </ul>
    </nav>
</body>
{% endblock content %}

templates/planWorkouts.html
{% include 'navbar.html' %}
{% load static %}
{% block content %}
<div class="planWorkouts">
    <div id="title">
        <p id="desc">{{ plan.name }} Information</p>
    </div>
    <p>
        <!-- check if there is workouts linked with a plan in the entire database-->
        {% if workoutToPlanList %}
        <ul>
            <!-- go through all workouts in the list-->
            {% for workoutL in workoutToPlanList %}
                <!-- Check if current plan is the same as given plan id-->
                {% if workoutL.plan_id == plan_id %}
                    <!-- Go through all workouts linked to a user in database-->
                    {% for workoutU in workoutToUserList %}
                        <!-- Check if current workout is linked to given user-->
                        {% if workoutU.user_id == user_id %}
                        {% if workoutL.workout_id == workoutU.id %}
                            <!-- go through all default workouts in database-->
                            {% for workoutD in workoutDefaultsList %}
                                <!-- Check if current default workout is the same as the user linked workout-->
                                {% if workoutD.id == workoutU.workout_id %}
                                <!-- Display information-->
                                    workout id: {{ workoutD.id }}<br>
                                    workout name:{{ workoutD.name }}<br>
                                    workout description: {{ workoutD.description }}<br>
                                    workout instructions: {{ workoutD.instructions }}<br>
                                    workout time: {{ workoutU.time }} minutes<br>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                        {% endif %}
                    {% endfor %}
                {% endif %}
            {% endfor %}
        </ul>
        {% else %}
            <p>No workouts in plan</p>
        {% endif %}
    </p>     
</div>
        
{% endblock content %}

templates/search.html
{% include 'navbar.html' %}
{% load static %}
{% block content %}

<center>
    {% if q %}
    <h1>Results for {{ q }}</h1>
    <br />
    {% for workout in workouts %}
    {{ workout.name }}<br />
    {% endfor %}

    {% else %}
    <h1>Search field empty</h1>

    {% endif %}

</center>

{% endblock %}